import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import './globals.css';
import Banner from '@/components/Banner';
import TanstackProvider from '@/providers/TanstackProvider';

const Vietnam = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['100', '400', '600', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className={`${Vietnam.className}`}>
        <TanstackProvider>
          <Banner />
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
